"""Contratos de repositório do salão (Repository Pattern com Interfaces)."""

from __future__ import annotations

import uuid
from typing import Protocol

from src.domain.entities.command import Command, CommandStatus
from src.domain.entities.queue_entry import QueueEntry
from src.domain.entities.table import Table


class TableRepositoryInterface(Protocol):
    async def get_by_id(self, table_id: uuid.UUID) -> Table | None: ...

    async def get_by_number(self, number: int) -> Table | None: ...

    async def list_all(self) -> list[Table]: ...

    async def add(self, table: Table) -> Table: ...

    async def save(self, table: Table) -> Table: ...


class CommandRepositoryInterface(Protocol):
    async def get_by_id(self, command_id: uuid.UUID) -> Command | None: ...

    async def get_open_command_for_table(self, table_id: uuid.UUID) -> Command | None: ...

    async def list_all(self, *, status: CommandStatus | None = None) -> list[Command]: ...

    async def add(self, command: Command) -> Command: ...

    async def save(self, command: Command) -> Command: ...


class QueueRepositoryInterface(Protocol):
    async def list_waiting(self) -> list[QueueEntry]: ...

    async def get_by_id(self, entry_id: uuid.UUID) -> QueueEntry | None: ...

    async def add(self, entry: QueueEntry) -> QueueEntry: ...

    async def save(self, entry: QueueEntry) -> QueueEntry: ...
