apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
  namespace: default
  labels:
    app: menu-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
        - name: menu-service
          image: restaurant-apps/menu-service:v0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: restaurant-platform-config
          env:
            - name: DB__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      name: http
  selector:
    app: menu-service
